package bluebit.fitbit.diagnostics

import android.bluetooth.BluetoothDevice
import android.bluetooth.BluetoothGatt
import android.bluetooth.BluetoothGattCallback
import android.bluetooth.BluetoothGattCharacteristic
import android.bluetooth.BluetoothGattDescriptor
import android.bluetooth.BluetoothProfile
import android.content.Context
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.util.Log
import java.util.UUID

/**
 * Diagnostic experiment for Fitbit Inspire 3 Gattlink transport layer.
 *
 * APK evidence:
 * - GattlinkService UUID = ABBAFF00 (server-side, matches Inspire 3 Service [4])
 * - ReceiveCharacteristic UUID = ABBAFF01 (WRITE_NO_RESPONSE)
 * - TransmitCharacteristic UUID = ABBAFF02 (NOTIFY + 0x2902 CCC)
 * - CCC subscribed value = {1, 0} (0x0100)
 * - STACK_NODE_DEFAULT_MTU = 185 (StackPeerKt.java)
 * - Gattlink frame format decoded from GattlinkPacket.Companion.parse()
 *
 * CRITICAL: The exact Gattlink initialization frame sequence is generated by
 * the native GoldenGate C/C++ library, not visible in Java decompilation.
 * Therefore this experiment is RECEIVE-ONLY — we enable notifications and
 * log any spontaneous frames from the Inspire 3, but do NOT transmit.
 */
class FitbitGattlinkDiagnostic(private val context: Context) {

    companion object {
        private const val TAG = "BlueBitGattlink"
        private const val EXPERIMENT_TIMEOUT_MS = 30000L

        private val GATTLINK_SERVICE_UUID = UUID.fromString("ABBAFF00-E56A-484C-B832-8B17CF6CBFE8")
        private val RECEIVE_CHARACTERISTIC_UUID = UUID.fromString("ABBAFF01-E56A-484C-B832-8B17CF6CBFE8")
        private val TRANSMIT_CHARACTERISTIC_UUID = UUID.fromString("ABBAFF02-E56A-484C-B832-8B17CF6CBFE8")
        private val CCC_DESCRIPTOR_UUID = UUID.fromString("00002902-0000-1000-8000-00805F9B34FB")

        private const val FITBIT_MTU = 185
    }

    private var gatt: BluetoothGatt? = null
    private var notificationsReceived = 0
    private var totalRxBytes = 0
    private val handler = Handler(Looper.getMainLooper())
    private var timeoutRunnable: Runnable? = null

    fun startExperiment(device: BluetoothDevice) {
        notificationsReceived = 0
        totalRxBytes = 0

        Log.i(TAG, "========== GATTLINK EXPERIMENT ==========")
        Log.i(TAG, "GATTLINK_EXPERIMENT_START")
        Log.i(TAG, "DEVICE_NAME=${device.name ?: "null"}")
        Log.i(TAG, "DEVICE_ADDRESS=${device.address}")
        Log.i(TAG, "APK_EVIDENCE:")
        Log.i(TAG, "  GATTLINK_SERVICE=$GATTLINK_SERVICE_UUID")
        Log.i(TAG, "  RECEIVE_CHAR=$RECEIVE_CHARACTERISTIC_UUID")
        Log.i(TAG, "  TRANSMIT_CHAR=$TRANSMIT_CHARACTERISTIC_UUID")
        Log.i(TAG, "  CCC_VALUE=0100")
        Log.i(TAG, "  REQUEST_MTU=$FITBIT_MTU")
        Log.i(TAG, "  NOTE: TX frames not sent — initialization sequence in native code")

        val callback = object : BluetoothGattCallback() {

            override fun onConnectionStateChange(gatt: BluetoothGatt, status: Int, newState: Int) {
                val stateName = when (newState) {
                    BluetoothProfile.STATE_CONNECTED -> "CONNECTED"
                    BluetoothProfile.STATE_DISCONNECTED -> "DISCONNECTED"
                    BluetoothProfile.STATE_CONNECTING -> "CONNECTING"
                    BluetoothProfile.STATE_DISCONNECTING -> "DISCONNECTING"
                    else -> "UNKNOWN($newState)"
                }
                Log.i(TAG, "CONNECTION_STATE status=$status newState=$stateName")

                if (newState == BluetoothProfile.STATE_CONNECTED && status == BluetoothGatt.GATT_SUCCESS) {
                    Log.i(TAG, "REQUESTING_MTU mtu=$FITBIT_MTU")
                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                        gatt.requestMtu(FITBIT_MTU)
                    } else {
                        Log.w(TAG, "MTU_REQUEST_NOT_SUPPORTED: API < 21")
                        gatt.discoverServices()
                    }
                } else if (newState == BluetoothProfile.STATE_DISCONNECTED) {
                    cancelTimeout()
                    this@FitbitGattlinkDiagnostic.gatt = null
                    Log.i(TAG, "GATT_DISCONNECTED")
                }
            }

            override fun onMtuChanged(gatt: BluetoothGatt, mtu: Int, status: Int) {
                Log.i(TAG, "MTU_CHANGED mtu=$mtu status=$status")
                gatt.discoverServices()
            }

            override fun onServicesDiscovered(gatt: BluetoothGatt, status: Int) {
                if (status != BluetoothGatt.GATT_SUCCESS) {
                    Log.e(TAG, "SERVICE_DISCOVERY_FAILED status=$status")
                    disconnect()
                    return
                }
                Log.i(TAG, "SERVICES_DISCOVERED status=0 services=${gatt.services.size}")

                val gattlinkService = gatt.services.find { it.uuid == GATTLINK_SERVICE_UUID }
                if (gattlinkService == null) {
                    Log.e(TAG, "SERVICE_NOT_FOUND uuid=$GATTLINK_SERVICE_UUID")
                    disconnect()
                    return
                }
                Log.i(TAG, "SERVICE_FOUND uuid=${gattlinkService.uuid} type=${gattlinkService.type}")

                val receiveChar = gattlinkService.getCharacteristic(RECEIVE_CHARACTERISTIC_UUID)
                val transmitChar = gattlinkService.getCharacteristic(TRANSMIT_CHARACTERISTIC_UUID)

                if (receiveChar == null) {
                    Log.e(TAG, "RECEIVE_CHARACTERISTIC_NOT_FOUND uuid=$RECEIVE_CHARACTERISTIC_UUID")
                } else {
                    Log.i(TAG, "RECEIVE_CHARACTERISTIC_FOUND uuid=${receiveChar.uuid} properties=${decodeProperties(receiveChar.properties)}")
                }

                if (transmitChar == null) {
                    Log.e(TAG, "TRANSMIT_CHARACTERISTIC_NOT_FOUND uuid=$TRANSMIT_CHARACTERISTIC_UUID")
                    disconnect()
                    return
                }
                Log.i(TAG, "TRANSMIT_CHARACTERISTIC_FOUND uuid=${transmitChar.uuid} properties=${decodeProperties(transmitChar.properties)}")

                val cccDescriptor = transmitChar.getDescriptor(CCC_DESCRIPTOR_UUID)
                if (cccDescriptor == null) {
                    Log.e(TAG, "CCC_DESCRIPTOR_NOT_FOUND uuid=$CCC_DESCRIPTOR_UUID")
                    disconnect()
                    return
                }
                Log.i(TAG, "CCC_DESCRIPTOR_FOUND uuid=${cccDescriptor.uuid}")

                // Enable notifications: write {1, 0} to CCC
                cccDescriptor.value = byteArrayOf(0x01, 0x00)
                Log.i(TAG, "NOTIFICATION_ENABLE_REQUESTED ccc=0100")
                val cccResult = gatt.writeDescriptor(cccDescriptor)
                Log.i(TAG, "CCC_WRITE_QUEUED result=$cccResult")
            }

            override fun onDescriptorWrite(gatt: BluetoothGatt, descriptor: BluetoothGattDescriptor, status: Int) {
                if (descriptor.uuid == CCC_DESCRIPTOR_UUID) {
                    Log.i(TAG, "CCC_WRITE_COMPLETE status=$status")
                    if (status == BluetoothGatt.GATT_SUCCESS) {
                        Log.i(TAG, "NOTIFICATIONS_ACTIVE")
                        // Start timeout — wait for spontaneous notifications
                        startTimeout(gatt)
                    } else {
                        Log.e(TAG, "CCC_WRITE_FAILED")
                        disconnect()
                    }
                }
            }

            override fun onCharacteristicChanged(gatt: BluetoothGatt, characteristic: BluetoothGattCharacteristic, value: ByteArray) {
                if (characteristic.uuid == TRANSMIT_CHARACTERISTIC_UUID) {
                    handleGattlinkRx(value)
                }
            }

            @Deprecated("Deprecated in Java")
            override fun onCharacteristicChanged(gatt: BluetoothGatt, characteristic: BluetoothGattCharacteristic) {
                if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) {
                    @Suppress("DEPRECATION")
                    onCharacteristicChanged(gatt, characteristic, characteristic.value ?: byteArrayOf())
                }
            }
        }

        gatt = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            device.connectGatt(context, false, callback, BluetoothDevice.TRANSPORT_LE)
        } else {
            @Suppress("DEPRECATION")
            device.connectGatt(context, false, callback)
        }
    }

    private fun handleGattlinkRx(value: ByteArray) {
        notificationsReceived++
        totalRxBytes += value.size

        Log.i(TAG, "RX_PACKET notificationsReceived=$notificationsReceived length=${value.size}")
        Log.i(TAG, "RX_HEX=${value.joinToString("") { "%02X".format(it) }}")

        // Parse using APK GattlinkPacket.Companion.parse() logic
        if (value.isEmpty()) {
            Log.w(TAG, "  FRAME_EMPTY")
            return
        }

        val firstByte = value[0].toInt() and 0xFF
        val isControl = (firstByte and 0x80) != 0
        val hasAck = (firstByte and 0x40) != 0
        val psn = firstByte and 0x1F

        val ackPsn: Int? = if (hasAck) psn else null
        val dataPsn: Int? = when {
            isControl -> null
            !hasAck -> psn
            value.size > 1 -> value[1].toInt() and 0x1F
            else -> null
        }

        Log.i(TAG, "  FRAME_DECODE:")
        Log.i(TAG, "    firstByte=0x${"%02X".format(firstByte)}")
        Log.i(TAG, "    isControl=$isControl")
        Log.i(TAG, "    hasAck=$hasAck")
        Log.i(TAG, "    psn=$psn")
        Log.i(TAG, "    ackPsn=$ackPsn")
        Log.i(TAG, "    dataPsn=$dataPsn")
        Log.i(TAG, "    payloadLength=${value.size - if (!isControl && hasAck && value.size > 1) 2 else 1}")

        // Show payload bytes (skip header)
        val headerSize = when {
            isControl -> 1
            hasAck && value.size > 1 -> 2
            else -> 1
        }
        if (value.size > headerSize) {
            val payload = value.sliceArray(headerSize until value.size)
            Log.i(TAG, "    payloadHex=${payload.joinToString("") { "%02X".format(it) }}")
        }
    }

    private fun startTimeout(gatt: BluetoothGatt) {
        val runnable = Runnable {
            Log.i(TAG, "TIMEOUT_EXPIRED notificationsReceived=$notificationsReceived totalRxBytes=$totalRxBytes")
            disconnect()
        }
        timeoutRunnable = runnable
        handler.postDelayed(runnable, EXPERIMENT_TIMEOUT_MS)
        Log.i(TAG, "TIMEOUT_STARTED ms=$EXPERIMENT_TIMEOUT_MS")
    }

    private fun cancelTimeout() {
        timeoutRunnable?.let { handler.removeCallbacks(it) }
        timeoutRunnable = null
    }

    fun disconnect() {
        cancelTimeout()
        val g = gatt
        if (g == null) {
            Log.w(TAG, "DISCONNECT_NO_GATT")
            return
        }
        Log.i(TAG, "DISCONNECTING notificationsReceived=$notificationsReceived totalRxBytes=$totalRxBytes")
        g.disconnect()
        g.close()
        gatt = null
        Log.i(TAG, "DISCONNECTED")
        Log.i(TAG, "========== END GATTLINK EXPERIMENT ==========")
    }

    private fun decodeProperties(properties: Int): String {
        val list = mutableListOf<String>()
        if (properties and BluetoothGattCharacteristic.PROPERTY_READ != 0) list.add("READ")
        if (properties and BluetoothGattCharacteristic.PROPERTY_WRITE != 0) list.add("WRITE")
        if (properties and BluetoothGattCharacteristic.PROPERTY_WRITE_NO_RESPONSE != 0) list.add("WRITE_NO_RESPONSE")
        if (properties and BluetoothGattCharacteristic.PROPERTY_NOTIFY != 0) list.add("NOTIFY")
        if (properties and BluetoothGattCharacteristic.PROPERTY_INDICATE != 0) list.add("INDICATE")
        return if (list.isEmpty()) "NONE(0x${properties.toString(16)})" else list.joinToString(", ")
    }
}
